title: Alp Ozkan - Product Executive
email: alpozkanm@gmail.com
description: Entrepreneur, Engineer, Product Executive.
url: "https://www.alpozkan.info/"
twitter_username: alpozkanm
github_username:  alpozkanm
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-readme-index
  - jekyll-analytics
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - INDEX.md