title: Alp Ozkan - Product Executive
email: alpozkanm@gmail.com
description:  >
As a seasoned Product Executive with over 10 years of experience, I have consistently delivered groundbreaking products in diverse industries such as E-commerce, FinTech, Delivery Service, Blockchain, and Mobile Apps.
My proven track record includes successfully launching more than 75 products on an international scale. Adept at building robust product organizations, I possess a keen understanding of every stage of product development, from early ideation to launch.
url: "https://www.alpozkan.info/"
twitter_username: alpozkanm
github_username:  alpozkanm
remote_theme: pages-themes/cayman@v0.2.0
google_analytics: G-T72L2FK7E3
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-readme-index
  - jekyll-analytics
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - INDEX.md